name: cinema_flt
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  carousel_slider: ^3.0.0
  flutter_swiper: ^1.1.6
  snaplist: ^0.1.8
  flutter_rating_bar: ^3.2.0+1
  intl: ^0.16.1
  flutter_tags: ^0.4.9+1
  shimmer: ^1.1.2
  rxdart: ^0.25.0
  pull_to_refresh: ^1.6.4
  cached_network_image: ^2.5.0

  provider: ^4.3.3
  logging: ^0.11.4
  json_serializable: ^3.5.1
  json_annotation: ^3.1.1
  # moor_flutter: ^2.1.1
  dio: ^3.0.10
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  equatable: ^1.2.6
  path_provider: ^1.6.27
  responsive_builder: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  # moor_generator: ^2.1.1
  mockito: ^4.1.4
  test: ^1.15.7
  hive_generator: ^0.8.2
  build_runner: ^1.11.1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/placeholder.png
   - assets/images/icon_movie.png
   - assets/images/icon_not_found.png
   - assets/images/logo_cinema.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
